audit/urls.py
from django.conf.urls import patterns, include, url
from account.views import *
from . import views

urlpatterns = [
    url(r'^operate_log$', views.operate_log, name='operate_log'),
]

deploy/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^key_manager/$', views.key_manager, name='key_manager'),
    url(r'^refresh_salt_host/$', views.refresh_salt_host, name='refresh_salt_host'),
]

hxoms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^asset/', include('assets.urls')),
    url(r'^deploy/', include('deploy.urls')),
    url(r'^audit/', include('audit.urls')),
    url(r'^$', views.index, name='index'),

]

deploy/models.py
#coding: utf-8

from __future__ import unicode_literals

from django.db import models
from assets.models import Server

key_status = (
    (1, "Accepted"),
    (2, "Unaccepted"),
    (3, "Deleted"),
)

# Create your models here.
class SaltHost(models.Model):
    node_name =  models.CharField(unique=True, max_length=50, verbose_name=u'主机名称')
    server = models.ForeignKey(Server, blank=True, null=True, on_delete=models.SET_NULL, verbose_name=u'主机')
    key_status = models.IntegerField(choices=key_status, blank=True, null=True, verbose_name=u'Key状态', default=1)

    def __str__(self):
        return self.node_name
    __repr__ = __str__

    class Meta:
        verbose_name = u'salt主机管理'
        verbose_name_plural = u'salt主机管理'

deploy/views.py
#coding: utf-8

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,JsonResponse,HttpResponseBadRequest,StreamingHttpResponse,Http404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from deploy.models import SaltHost
from assets.models import Server
from assets.tasks import operate_log
from ConfigParser import ConfigParser
from api.saltapi import SaltAPI
from django.db.models import Q 

CONFIG_FILE="./hxoms/config.ini"
config=ConfigParser()
config.read(CONFIG_FILE)

# Create your views here.
@login_required
def key_manager(request):
    sapi = SaltAPI(url=config.get('saltapi','url'), username=config.get('saltapi','username'), password=config.get('saltapi','password'))
    node_name = request.GET.get('minion_id', "")
    action = request.GET.get('action', "")
    #print(node_name)
    #print(action)
    if node_name:
        salthost = get_object_or_404(SaltHost, node_name=node_name)
        if action == "delete_key":
            sapi.delete_key(node_name)
            salthost.key_status = 3
            if salthost.server:
                salthost.server.node_name = None
                salthost.server.alive = False
                salthost.server.save()
            salthost.save()
            operate_log.delay(user=request.user.username,ip=request.META.get('HTTP_X_FORWARDED_FOR',request.META['REMOTE_ADDR']),type=u"删除Key",content=u"删除Key：{}".format(node_name))
            return JsonResponse({"status": u"删除成功"})
        if action == "accept_key":
            sapi.accept_key(node_name)
            salthost.key_status = 1
            salthost.save()
            operate_log.delay(user=request.user.username,ip=request.META.get('HTTP_X_FORWARDED_FOR',request.META['REMOTE_ADDR']),type=u"接受Key",content=u"接受Key：{}".format(node_name))
            return JsonResponse({"status": u"接受成功"})
        if action == "refresh_host":
            try:
                server = Server.objects.get(node_name=node_name)
            except ObjectDoesNotExist:
                server = None
            if server:
                online = sapi.salt_alive(server.node_name)
                if not online:
                    server.alive = False
                else:
                    server.alive = True
                server.save()
            salthost.server = server
            salthost.save()
            if server:
                return JsonResponse({"status": u"刷新完成","host": server.ip, "alive": server.alive, "id": server.id})
            else:
                return JsonResponse({"status": u"刷新完成","server": server})
        if action == "refresh_status":
            minions,minions_pre = sapi.list_all_key()
            if node_name in minions_pre:
                salthost.key_status = 2
                salthost.save()
                return JsonResponse({"status": u"刷新完成"})
        if action == "delete":
            salthost.delete()
            return JsonResponse({"status": u"删除成功"})
    minions = SaltHost.objects.filter(key_status=1)
    minions_pre = SaltHost.objects.filter(~Q(key_status=1))
    return render(request, 'key_manager.html', locals())

@login_required
def refresh_salt_host(request):
    sapi = SaltAPI(url=config.get('saltapi','url'), username=config.get('saltapi','username'), password=config.get('saltapi','password'))
    minions,minions_pre = sapi.list_all_key()
    for node_name in minions:
        obj,created = SaltHost.objects.get_or_create(node_name=node_name)
        obj.key_status = 1
        try:
            obj.server = Server.objects.get(node_name=node_name)
        except ObjectDoesNotExist:
            obj.server = None
        obj.save()
    for node_name in minions_pre:
        obj,created = SaltHost.objects.get_or_create(node_name=node_name)
        obj.key_status = 2
        try:
            obj.server = Server.objects.get(node_name=node_name)
        except ObjectDoesNotExist:
            obj.server = None
        obj.save()
    operate_log.delay(user=request.user.username,ip=request.META.get('HTTP_X_FORWARDED_FOR',request.META['REMOTE_ADDR']),type=u"导入主机",content=u"导入salt主机")
    return JsonResponse({"status": u"刷新完成"})

deploy/templates/key_manager.html
{% extends "base.html" %}

{% block css %}
<script src="/static/js/jquery-1.11.0.min.js"></script>
<script src="/static/plugins/xcConfirm/js/xcConfirm.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/static/plugins/xcConfirm/css/xcConfirm.css"/>
<link rel="stylesheet" type="text/css" href="/static/plugins/jquery.mloading/src/jquery.mloading.css"/>
<link rel="stylesheet" type="text/css" href="/static/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="/static/css/hxoms.css"/>
<style>
tr>th, tr>td {
    font-size: 12px;
}
</style>
{% endblock %}

{% block content %}
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Salt Key管理
           <span class="pull-right">
             <a href="{% url 'refresh_salt_host' %}" type="button"
             class="btn btn-primary btn-xs refresh_salt_host"
             title="有添加或minion id有修改需要重新刷新主机" onclick="refresh_salt_host(this);return false">刷新salt主机</a>
           </span>
         </h3>
		</div>
  		<div class="panel-body">
        <div style="color:green">
          <b>Accepted Key</b>
          <p></p>
        </div>
 		  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered accepted">
  			<thead>
  			      <tr>
  			        <th>Minion ID</th>
  			        <th>主机</th>
  			        <th>在线状态</th>
                 <th>操作</th>
  			      </tr>
  			    </thead>
  			<tbody>
           {% for minion in minions %}
		       <tr class="gradeA">
  			      <td>{{ minion.node_name }}</td>
               {% if minion.server %}
                 <td><a href="{% url 'server_detail' id=minion.server.id %}" title="详细信息">{{ minion.server.ip }}</a></td>
                 <td>{% if minion.server.alive %}<span style="color:green">online</span>{% else %}<span style="color:red">offline</span>{% endif %}</td>
               {% else %}
                 <td><a href="#">{{minion.server}}</a></td>
                 <td><span>{{minion.server}}</span></td>
               {% endif %}
               <td>
                 <a href="{% url 'key_manager' %}?minion_id={{ minion.node_name }}&action=delete_key" class="btn btn-danger btn-xs" title="删除key" onclick="del_key(this);return false"><i class="glyphicon glyphicon-trash"></i></a>
                 <a href="{% url 'key_manager' %}?minion_id={{ minion.node_name }}&action=refresh_host" class="btn btn-success btn-xs" id="refresh_host" title="刷新主机" onclick="return false"><i class="glyphicon glyphicon-refresh"></i></a>
               </td>
  			    </tr>
           {% endfor %}
  			</tbody>
		  </table>
        <div></div>
        <div style="color:orange">
          <b>Unaccepted&Deleted Key</b>
          <p></p>
        </div>
 		  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered unaccepted">
  			<thead>
  			      <tr>
  			        <th>Minion ID</th>
  			        <th>Key状态</th>
                 <th>操作</th>
  			      </tr>
  			    </thead>
  			<tbody>
           {% for minion in minions_pre %}
		       <tr class="gradeA">
  			      <td>{{ minion.node_name }}</td>
               <td>
                 {% ifequal minion.key_status 2 %}
                   <span style="color:orange">{{ minion.get_key_status_display }}</span>
                 {% else %}
                   <span style="color:red">{{ minion.get_key_status_display }}</span>
                 {% endifequal %}
               </td>
               <td>
                 {% ifequal minion.key_status 2 %}
                   <a href="{% url 'key_manager' %}?minion_id={{ minion.node_name }}&action=accept_key" class="btn btn-info btn-xs" title="接受key" onclick="accept_key(this);return false"><i class="glyphicon glyphicon-plus"></i></a>
                 {% else %}
                   <a href="{% url 'key_manager' %}?minion_id={{ minion.node_name }}&action=delete" class="btn btn-danger btn-xs" title="删除" onclick="del(this);return false"><i class="glyphicon glyphicon-trash"></i></a>
                   <a href="{% url 'key_manager' %}?minion_id={{ minion.node_name }}&action=refresh_status" class="btn btn-success btn-xs" id="refresh_status" title="刷新状态"onclick="return false"><i class="glyphicon glyphicon-refresh"></i></a>
                 {% endifequal %}
               </td>
  			    </tr>
           {% endfor %}
  			</tbody>
		</div>
	</div>  <!--panel end-->
</div>
{% endblock %}

{% block js %}
<script src="/static/js/validators.js"></script>
<script src="/static/plugins/jquery.mloading/src/jquery.mloading.js" type="text/javascript"></script>
<script>
$(document).ready(function() {
    /* Normal */
    $('.accepted').dataTable({
      "aLengthMenu" : [5, 10, 15], //更改显示记录数选项
      "iDisplayLength" : 5, //默认显示的记录数
      "bSort": true,
      "aaSorting" : [[2,"desc"],[1, "asc"]], //默认的排序方式，第2列，升序排列
      "sPaginationType": "bs_full",
    }); 
    $('.accepted').each(function(){
      var datatable = $(this);
      // SEARCH - Add the placeholder for Search and Turn this into in-line form control
      var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
      search_input.attr('placeholder', 'Search');
      search_input.addClass('form-control input-sm');
      // LENGTH - Inline-Form control
      var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
      length_sel.addClass('form-control input-sm');
    });
    $('.unaccepted').dataTable({
      "aLengthMenu" : [5, 10, 15], //更改显示记录数选项
      "iDisplayLength" : 5, //默认显示的记录数
      "bSort": true,
      "aaSorting" : [[1, "desc"]], //默认的排序方式，第2列，升序排列
      "sPaginationType": "bs_full",
    }); 
    $('.unaccepted').each(function(){
      var datatable = $(this);
      // SEARCH - Add the placeholder for Search and Turn this into in-line form control
      var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
      search_input.attr('placeholder', 'Search');
      search_input.addClass('form-control input-sm');
      // LENGTH - Inline-Form control
      var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
      length_sel.addClass('form-control input-sm');
    });

    $('[id=refresh_host]').click(function(){
        var wid=$(this)
        var url=wid.attr("href")
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
        $("body").mLoading({
            text:"刷新中...",//加载文字，默认值：加载中...
            icon:"/static/img/indicator.gif",//加载图标，默认值：一个小型的base64的gif图片
            mask:true,//是否显示遮罩效果，默认显示
        });
        $.ajax({
            type:"GET",
            url:url,
            success: function(ret){
                if(ret["status"]=="刷新完成"){
                    if(ret["server"] === null){
                        wid.parent().prev().find("span").text("None")
                        wid.parent().prev().find("span").css("color", "")
                        wid.parent().prev().prev().find("a").text("None")
                        wid.parent().prev().prev().find("a").attr({"href":"#", "title":""})
                    }else{
                        if(ret["alive"]){
                            wid.parent().prev().find("span").text("online")
                            wid.parent().prev().find("span").css("color", "green")
                        }else{
                            wid.parent().prev().find("span").text("offline")
                            wid.parent().prev().find("span").css("color", "red")
                        }
                        wid.parent().prev().prev().find("a").text(ret["host"])
                        wid.parent().prev().prev().find("a").attr({"href":"/asset/server_detail/"+ret["id"], "title":"详细信息"})
                    }
                    $("body").mLoading("hide")
                }
                else{
                    $("body").mLoading("hide")
                    window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                }
            }
        })
    });
    $('[id=refresh_status]').click(function(){
        var wid=$(this)
        var parent = wid.parent()
        var url=wid.attr("href")
        var node_name = wid.parent().prev().prev().text()
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
        $("body").mLoading({
            text:"刷新中...",//加载文字，默认值：加载中...
            icon:"/static/img/indicator.gif",//加载图标，默认值：一个小型的base64的gif图片
            mask:true,//是否显示遮罩效果，默认显示
        });
        $.ajax({
            type:"GET",
            url:url,
            success: function(ret){
                if(ret["status"]=="刷新完成"){
                    parent.prev().find("span").text("Unaccepted")
                    parent.prev().find("span").css("color", "orange")
                    parent.find("a").remove()
                    parent.append('<a href="/deploy/key_manager/?minion_id='+node_name+'&action=accept_key" class="btn btn-info btn-xs" title="接受key" onclick="accept_key(this);return false"><i class="glyphicon glyphicon-plus"></i></a>')
                    $("body").mLoading("hide")
                }
                else{
                    $("body").mLoading("hide")
                    //window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                }
            }
        })
    });
});
function refresh_salt_host(obj){
    var url=$(obj).attr("href")
    var option = {
        onOk: function(){
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $("body").mLoading({
                text:"刷新中...",//加载文字，默认值：加载中...
                icon:"/static/img/indicator.gif",//加载图标，默认值：一个小型的base64的gif图片
                mask:true,//是否显示遮罩效果，默认显示
            });
            $.ajax({
                type:"GET",
                url:url,
                success: function(ret){
                    if(ret["status"]=="刷新完成"){
                        window.location.reload();
                    }
                    else{
                        window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                    }
                }
            })
        },
    }
    window.wxc.xcConfirm("确认刷新salt主机？", window.wxc.xcConfirm.typeEnum.warning, option);
};

function del_key(obj){
    var url=$(obj).attr("href")
    var node_name = $(obj).parent().prev().prev().prev().text()
    var option = {
        onOk: function(){
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $("body").mLoading({
                text:"删除中...",//加载文字，默认值：加载中...
                icon:"/static/img/indicator.gif",//加载图标，默认值：一个小型的base64的gif图片
                mask:true,//是否显示遮罩效果，默认显示
            });
            $.ajax({
                type:"GET",
                url:url,
                success: function(ret){
                    if(ret["status"]=="删除成功"){
                        window.location.reload();
                    }
                    else{
                        window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                    }
                }
            })
        },
    }
    window.wxc.xcConfirm("确认删除Key："+node_name+"?", window.wxc.xcConfirm.typeEnum.warning, option);
};

function accept_key(obj){
    var url=$(obj).attr("href")
    $.ajax({
        type:"GET",
        url:url,
        success: function(ret){
            if(ret["status"]=="接受成功"){
                window.location.reload();
            }
            else{
                window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
            }
        }
    })
};

function del(obj){
    var url=$(obj).attr("href")
    var node_name = $(obj).parent().prev().prev().text()
    var option = {
        onOk: function(){
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $.ajax({
                type:"GET",
                url:url,
                success: function(ret){
                    if(ret["status"]=="删除成功"){
                        window.location.reload();
                    }
                    else{
                        window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                    }
                }
            })
        },
    }
    window.wxc.xcConfirm("此操作会将记录从数据库中删除，确认删除"+node_name+"?", window.wxc.xcConfirm.typeEnum.warning, option);
};
</script>
{% endblock %}