assets/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^idc_list/$', views.idc_list, name='idc_list'),
    url(r'^idc_operate/(?P<id>\d+)/$', views.idc_operate, name='idc_operate'),
    url(r'^server_list/$', views.server_list, name='server_list'),
    url(r'^server_operate/(?P<id>\d+)/$', views.server_operate, name='server_operate'),
    url(r'^server_detail/(?P<id>\d+)/$', views.server_detail, name='server_detail'),
    url(r'^server_update/$', views.update_serverinfo, name='server_update'),
    url(r'^status_change/(?P<sid>\d+)/(?P<status>\d)/$', views.status_change, name='status_change'),
    url(r'^supplier_list/$', views.supplier_list, name='supplier_list'),
    url(r'^supplier_operate/(?P<id>\d+)/$', views.supplier_operate, name='supplier_operate'),
    url(r'^contract_download/(?P<id>\d+)/$', views.contract_download, name='contract_download'),
    #url(r'^supplier_operate/$', views.supplier_operate, name='supplier_add'),
    url(r'^service_list/$', views.service_list, name='service_list'),
    url(r'^service_operate/(?P<id>\d+)/$', views.service_operate, name='service_operate'),
    url(r'^requisition_list/$', views.requisition_list, name='requisition_list'),
    url(r'^requisition_operate/(?P<id>\d+)/$', views.requisition_operate, name='requisition_operate'),
    url(r'^requisition_renew/(?P<id>\d+)/(?P<renew>\d)/$', views.requisition_operate, name='requisition_renew'),
    url(r'^requisition_renew_list/$', views.requisition_renew_list, name='requisition_renew_list'),
    url(r'^req_approve/(?P<id>\d+)/(?P<result>\w{2,3})/$', views.req_approve, name='req_approve'),
    url(r'^pay_confirm/(?P<id>\d+)/$', views.pay_confirm, name='pay_confirm'),
    url(r'^cost_show/$', views.cost_show, name='cost_show'),
    #url(r'^idc_add/$', views.idc_manage, name='idc_add'),
    #url(r'^idc_edit/(?P<id>\d+)/$', views.idc_manage, name='idc_edit'),
    #url(r'^idc_delete/$', views.idc_manage, name='idc_delete'),
    #url(r'^asset_list/$', views.asset_list, name='asset_list'),
    #url(r'^asset_add/$', views.asset_manage, name='asset_add'),
    #url(r'^asset_edit/(?P<id>\d+)/$', views.asset_manage, name='asset_edit'),
    #url(r'^asset_delete/$', views.asset_manage, name='asset_delete'),
    #url(r'^asset_detail/(?P<id>\d+)/$', views.asset_detail, name='asset_detail'),
    #url(r'^host_list/$', views.host_list, name='host_list'),
    #url(r'^host_add/$', views.host_manage, name='host_add'),
    #url(r'^host_update/(?P<id>\d+)/$', views.host_manage, name='host_update'),
    #url(r'^host_delete/$', views.host_manage, name='host_delete'),
]

audit/urls.py
from django.conf.urls import patterns, include, url
from account.views import *
from . import views

urlpatterns = [
    url(r'^operate_log$', views.operate_log, name='operate_log'),
]

hxoms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^asset/', include('assets.urls')),
    url(r'^deploy/', include('deploy.urls')),
    url(r'^audit/', include('audit.urls')),
    url(r'^$', views.index, name='index'),

]

assets/models.py
# coding:utf-8

from __future__ import unicode_literals

from django.db import models

idc_type = (
    ('DX', u'电信'),
    ('LT', u'联通'),
    ('YD', u'移动'),
    ('ZJ', u'自建'),
)

asset_status = (
    (1, u"正常"),
    (2, u"停用"),
)

server_type = (
    (1, u"物理机"),
    (2, u"虚拟机"),
    (3, u"容器"),
)

payment = (
    (1, u"银行支付"),
    (2, u"支付宝支付"),
)

payment_status = (
    (1, u"待付款"),
    (2, u"已付款"),
    (3, u"待续费"),
    (4, u"已申请续费"),
)

approve_status = (
    (1, u"待审核"),
    (2, u"已通过"),
    (3, u"未通过"),
)

unit = (
    (1, u"人民币 CNY"),
    (2, u"港币 HKD"),
    (3, u"美金 USD"),
)

def contract_dir_path(instance, filename):
    return 'contract/{0}/{1}'.format(instance.name, filename)

# Create your models here.
class Idc(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name=u'机房名字')
    address = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'机房地址')
    type = models.CharField(choices=idc_type, max_length=20, verbose_name=u'机房类型', default='DX')
    bandwidth = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'机房带宽')
    contact = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'联系人')
    phone = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'联系电话')
    email = models.EmailField(blank=True, null=True, verbose_name=u'邮箱')
    def __str__(self):
        return self.name
    __repr__ = __str__

    class Meta:
        verbose_name = u'机房'
        verbose_name_plural = u'机房列表'

class Server(models.Model):
    ip = models.GenericIPAddressField(unique=True, verbose_name='IP')
    node_name = models.CharField(blank=True, null=True, max_length=50, verbose_name="Minion ID")

    idc = models.ForeignKey(Idc, blank=True, null=True, on_delete=models.PROTECT, verbose_name=u'所属机房')
    cabinet = models.CharField(blank=True,null=True,  max_length=30, verbose_name=u'机柜号')
    position = models.PositiveIntegerField(blank=True, null=True, verbose_name=u'机器位置')

    status = models.IntegerField(choices=asset_status, blank=True, null=True, verbose_name=u'状态', default=1)
    alive = models.BooleanField(default=False, verbose_name=u'在线状态')
    create_date = models.DateField(blank=True, null=True, auto_now_add=True, verbose_name=u"创建日期")
    end_date = models.DateField(null=True, blank=True, verbose_name=u'到期日期')
    cost = models.CharField(blank=True, null=True, max_length=20, verbose_name=u"购买费用")
    use = models.TextField(blank=True, null=True, max_length=100, verbose_name=u'作用')

    def __str__(self):
        return self.ip
    __repr__ = __str__

    class Meta:
        verbose_name = u'服务器'
        verbose_name_plural = u'服务器列表'

class ServerInfo(models.Model):
    ip = models.OneToOneField(Server, verbose_name="IP")
    other_ip = models.CharField(blank=True, null=True, max_length=100, verbose_name=u"其他IP")
    #remote_ip = models.GenericIPAddressField(blank=True ,null=True ,verbose_name=u'远控卡IP')
    hostname = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'主机名')
    hwaddr = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'MAC地址')

    manufacturer = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'厂商')
    brand = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'产品型号')

    cpu = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'CPU型号')
    cpu_num = models.PositiveSmallIntegerField(verbose_name=u'CPU核数')
    memory = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'内存')
    disk = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'硬盘')

    system_type = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'系统类型')
    system_version = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'系统版本')
    system_arch = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'系统平台')

    #type = models.IntegerField(choices=server_type, blank=True, null=True, verbose_name=u'类型', default=1)
    virtual = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'虚拟环境')
    # 同一个表中，OneToOneField和ForeignKey不能同时关联同一个对象，所以这里只能关联self
    vm = models.ForeignKey("self", blank=True, null=True, on_delete=models.PROTECT, verbose_name=u'宿主机')
    sn = models.CharField(blank=True, null=True, max_length=100, verbose_name=u'序列号')

    def __str__(self):
        return self.ip.ip
    __repr__ = __str__

    class Meta:
        verbose_name = u'服务器信息'
        verbose_name_plural = u'服务器信息列表'

class Supplier(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name=u"供应商名称")
    website = models.CharField(blank=True, null=True, max_length=100,verbose_name=u"网站")
    # FileField默认会自动上传文件，不需要通过chunk操作保存
    contract = models.FileField(blank=True, null=True, upload_to=contract_dir_path, verbose_name=u"合同")
    business = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'业务联系人')
    bus_phone = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'业务联系人电话')
    technical = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'业务联系人')
    tec_phone = models.CharField(blank=True, null=True, max_length=20, verbose_name=u'技术联系人电话')
    email = models.EmailField(blank=True, null=True, verbose_name=u'邮箱')
    comment = models.TextField(blank=True, null=True, max_length=100, verbose_name=u'备注')

    def __str__(self):
        return self.name
    __repr__ = __str__

    class Meta:
        verbose_name = u'供应商'
        verbose_name_plural = u'供应商列表'
    

# 互联网服务资产类型，例如：adsl、域名等
class Type(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name=u'类型名称')

    def __str__(self):
        return self.name
    __repr__ = __str__

    class Meta:
        verbose_name = u'服务类型'
        verbose_name_plural = u'服务类型列表'

class Service(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name=u"服务名称")
    type = models.ForeignKey(Type, blank=True, null=True ,verbose_name=u"服务类型")
    supplier = models.ForeignKey(Supplier, blank=True, null=True, on_delete=models.PROTECT, verbose_name=u"供应商")
    use = models.TextField(blank=True, null=True, max_length=100, verbose_name=u"作用")
    backstage = models.CharField(blank=True, null=True, max_length=128, verbose_name=u"后台地址")
    status = models.IntegerField(choices=asset_status, blank=True, null=True, verbose_name=u'状态', default=1)
    
    create_date = models.DateField(blank=True, null=True, auto_now_add=True, verbose_name=u"创建日期")
    end_date = models.DateField(null=True, blank=True, verbose_name=u'到期日期')
    cost = models.CharField(blank=True, null=True, max_length=20, verbose_name=u"购买费用")

    def __str__(self):
        return self.name
    __repr__ = __str__

    class Meta:
        verbose_name = u'服务'
        verbose_name_plural = u'服务列表'

class Requisition(models.Model):
    asset = models.CharField(blank=True, null=True, max_length=50, verbose_name=u"资产")
    payment = models.IntegerField(choices=payment, verbose_name=u"支付方式", default=1)
    info = models.CharField(blank=True, null=True, max_length=100, verbose_name=u"支付信息")
    cost = models.CharField(blank=True, null=True, max_length=20, verbose_name=u"申请单金额")
    unit = models.IntegerField(choices=unit, verbose_name=u'金额单位', default=1)
    payment_status = models.IntegerField(choices=payment_status, blank=True, null=True, verbose_name=u'付款状态', default=1)
    approve_status = models.IntegerField(choices=approve_status, blank=True, null=True, verbose_name=u'审批状态', default=1)
    create_time = models.DateTimeField(blank=True, null=True, auto_now_add=True, verbose_name=u"创建时间")
    end_date = models.DateField(null=True, blank=True, verbose_name=u'资产截止日期')
    comment = models.TextField(blank=True, null=True, max_length=100, verbose_name=u'备注')

    class Meta:                                                                 
        verbose_name = u'申请单'                                                  
        verbose_name_plural = u'申请单列表'

assets/forms.py
#coding: utf-8

from django import forms
from assets.models import Idc, Server, Supplier, Service, Requisition

class IdcForm(forms.ModelForm):
    class Meta:
        model = Idc
        fields = ('name', 'address', 'type', 'bandwidth', 'contact', 'phone', 'email')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'bandwidth': forms.TextInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'pattern': '^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'pattern': '.+@.+\.[a-zA-Z]{2,4}$'}),
            #'start_date': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date', 'value': '1997-01-01'}),
            #'end_date': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date', 'value': '1997-01-01'}),
            #'cost': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = ('ip', 'idc', 'cabinet', 'position', 'cost', 'use')
        widgets = {
            'ip': forms.TextInput(attrs={'class': 'form-control'}),
            'idc': forms.Select(attrs={'class': 'form-control'}),
            'cabinet': forms.TextInput(attrs={'class': 'form-control'}),
            'position': forms.NumberInput(attrs={'class': 'form-control'}),
            'cost': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': u'单位(元/月)'}),
            'use': forms.Textarea(
                attrs={'class': 'form-control',
                       'placeholder': u'请输入100字以内',
                       'rows': '5'}),
        }

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ('name', 'website', 'business', 'bus_phone', 'technical', 'tec_phone', 'contract', 'email', 'comment')
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_name'}),
            'website': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_website'}),
            'business': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_business'}),
            'bus_phone': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_bus_phone'}),
            'technical': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_technical'}),
            'tec_phone': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'sup_tec_phone'}),
            'contract': forms.FileInput(
                attrs={'class': 'form-control',
                       'id': 'sup_contract'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control',
                       'id': 'sup_email'}),
            'comment': forms.Textarea(
                attrs={'class': 'form-control',
                       'id': 'sup_comment',
                       'placeholder': u'请输入100字以内',
                       'rows': '5'}),
        }

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'supplier', 'use', 'backstage', 'cost')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'supplier': forms.Select(attrs={'class': 'form-control'}),
            'use': forms.Textarea(
                attrs={'class': 'form-control',
                       'placeholder': u'请输入100字以内',
                       'rows': '5'}),
            'backstage': forms.TextInput(attrs={'class': 'form-control'}),
            'cost': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': u'单位(元/月)'}),
        }

class RequisitionForm(forms.ModelForm):
    class Meta:
        model = Requisition
        fields = ('payment', 'cost', 'unit', 'end_date', 'comment')
        widgets = {
            'payment': forms.Select(
                attrs={'class': 'form-control',
                       'id': 'id_payment'}),
            'cost': forms.TextInput(
                attrs={'class': 'form-control',
                       'id': 'id_cost'}),
            'unit': forms.Select(
                attrs={'class': 'form-control',
                       'id': 'id_unit'}),
            'end_date': forms.DateInput(
                attrs={'class': 'form-control',
                       'id': 'id_end_date',
                       'readonly': True}),
            'comment': forms.Textarea(
                attrs={'class': 'form-control',
                       'id': 'id_comment',
                       'placeholder': u'请输入100字以内',
                       'rows': '5'}),
        }

assets/templates/idc_list.html
{% extends "base.html" %}

{% block css %}
<script src="/static/js/jquery-1.11.0.min.js"></script>
<script src="/static/plugins/xcConfirm/js/xcConfirm.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/static/plugins/xcConfirm/css/xcConfirm.css"/>
<link rel="stylesheet" type="text/css" href="/static/css/reset.css"/>
<style>
tr>th, tr>td {
    font-size: 12px;
}
</style>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#idc-list" data-toggle="tab" onclick="return false;">机房列表</a>
    </li>
    <li>
	   <!--return false;防止切换时自动滑动到底部-->
      <a href="#idc-add" data-toggle="tab" onclick="return false;">机房添加</a>
    </li>
    <li class="pull-right"><h1 class="section-title">机房管理</h1></li>
  </ul>
</div>

<div class="tab-content">
  <div class="tab-pane active" id="idc-list">
    <div class="col-lg-12">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<h3 class="panel-title">机房列表</h3>
    		</div>
  			<div class="panel-body">
 				<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered bs_normal">
  			    <thead>
  			      <tr>
  			        <th>机房名字</th>
  			        <th>机房地址</th>
  			        <th>机房类型</th>
  			        <th>机房带宽</th>
  			        <th>联系人</th>
  			        <th>联系电话</th>
  			        <th>邮箱</th>
                 <th>操作</th>
  			      </tr>
  			    </thead>
  			    <tbody>
               {% for idc in idcs %}
    		        <tr class="gradeA">
  			          <td>{{ idc.name }}</td>
  			          <td>{{ idc.address }}</td>
                   <td>{{ idc.get_type_display }}</td>
  			          <td>{{ idc.bandwidth }}</td>
  			          <td class="center">{{ idc.contact }}</td>
  			          <td class="center">{{ idc.phone }}</td>
                   <td>{{ idc.email }}</td> 
                   <td>
                     <a href="{% url 'idc_operate' id=idc.id %}" title="编辑"><i class="glyphicon glyphicon-edit"></i></a>
                     <a href="{% url 'idc_operate' id=idc.id %}" style="color:red" title="删除" onclick="del(this);return false"><i class="glyphicon glyphicon-trash"></i></a>
                   </td>
  			        </tr>
               {% endfor %}
  			    </tbody>
  			   </table>
    		</div>
    	</div>  <!--panel end-->
    </div>
  </div>  <!--pane end-->
  <div class="tab-pane" id="idc-add">
    <div class="col-lg-12">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<h3 class="panel-title">机房添加</h3>
    		</div>
  			<div class="panel-body">
           <form class="form-horizontal form-border" id="form-add" method="post" action="">
             {% csrf_token %}
             <div class="form-group">
               <label class="control-label">机房名字</label>
               {{ form.name }}
             </div>
             <div class="form-group">
               <label class="control-label">机房地址</label>
               {{ form.address }}
             </div>
             <div class="form-group">
               <label class="control-label">机房类型</label>
               {{ form.type }}
             </div>
             <div class="form-group">
               <label class="control-label">机房带宽</label>
               {{ form.bandwidth }}
             </div>
             <div class="form-group">
               <label class="control-label">联系人</label>
               {{ form.contact }}
             </div>
             <div class="form-group">
               <label class="control-label">联系电话</label>
               {{ form.phone }}
             </div>
             <div class="form-group">
               <label class="control-label">邮箱</label>
               {{ form.email }}
             </div>
             <div>
               <button type="button" class="btn btn-primary btn-sm" id="add-btn">添加</button>
             </div>
           </form>
         </div>
      </div>
    </div>
  </div>
</div>  <!--content end-->
{% endblock %}

{% block js %}
<script src="/static/js/validators.js"></script>
<script>
$(document).ready(function() {
    /* Normal */
    $('.bs_normal').dataTable({
      "bSort": false,
      "sPaginationType": "bs_full",
    }); 
    $('.bs_normal').each(function(){
      var datatable = $(this);
      // SEARCH - Add the placeholder for Search and Turn this into in-line form control
      var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
      search_input.attr('placeholder', 'Search');
      search_input.addClass('form-control input-sm');
      // LENGTH - Inline-Form control
      var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
      length_sel.addClass('form-control input-sm');
    });

    $("#form-add input").blur(function(){
        //alert("test")
        var parent = $(this).parent();
        parent.find("#errorinfo").remove()
        parent.find("#feedback").remove()
        parent.removeClass("has-success")
        parent.removeClass("has-error")
        if($(this).is("#id_name")){
            //alert("test")
            $.checkName(this.value,parent,"请输入机房名字")
        }
        if($(this).is("#id_phone")){
            $.checkPhone(this.value,parent)
        }
        if($(this).is("#id_email")){
            $.checkEmail(this.value,parent)
        }
    });

    jQuery.fn.checkForm=function(){
        $("#form-add input:not(:hidden)").each(function () {
            var $parent = $(this).parent();
            //$parent.addClass("has-error has-feedback")
            $parent.find("#errorinfo").remove()
            $parent.find("#feedback").remove()
            $parent.removeClass("has-success")
            $parent.removeClass("has-error")
            if($(this).is("#id_name")){
                //alert("test")
                $.checkName(this.value,$parent,"请输入机房名字")
            }
            if($(this).is("#id_phone")){
                $.checkPhone(this.value,$parent)
            }
            if($(this).is("#id_email")){
                $.checkEmail(this.value,$parent)
            }
        });
    };
    $('#add-btn').click(function(){
        var name = $("#id_name").val()
        var address = $("#id_address").val()
        var type = $("#id_type").val()
        var bandwidth = $("#id_bandwidth").val()
        var contact = $("#id_contact").val()
        var phone = $("#id_phone").val()
        var email = $("#id_email").val()
        $('#form-add').checkForm();
        if($("#errorinfo").length == 0){
            //alert("不存在")
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $.ajax({
                type:"POST",
                url:"{% url 'idc_list' %}",
                data:{"name": name, "address": address, "type": type, "bandwidth": bandwidth, "contact": contact, "phone": phone, "email": email},
                dataType:"json",
                success: function(ret){
                    if(ret["status"]=="添加成功"){
                        $("#id_name").val("")
                        $("#id_address").val("")
                        $("#id_bandwidth").val("")
                        $("#id_contact").val("")
                        $("#id_phone").val("")
                        $("#id_email").val("")
                        var option = {
                            onOk: function(){
                               window.location.reload();
                            },
                            onClose:function(){
                               window.location.reload();
                            }
                        }
                        window.wxc.xcConfirm(ret["status"], window.wxc.xcConfirm.typeEnum.success,option);
                    }
                    else{
                        window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                    }
                }
            })
        }
        else{
            //alert("存在")
        }
    });
});
function del(obj){
    var url=$(obj).attr("href")
    var option = {
        onOk: function(){
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $.ajax({
                type:"DELETE",
                url:url,
                success: function(ret){
                    if(ret["status"]=="删除成功"){
                        window.location.reload();
                    }
                    else{
                        window.wxc.xcConfirm(ret["msg"], window.wxc.xcConfirm.typeEnum.error);
                    }
                }
            })
        },
    }
    window.wxc.xcConfirm("删除后将不可恢复！确认删除？", window.wxc.xcConfirm.typeEnum.warning, option);
};
</script>
{% endblock %}